---
framework: mocha
preRun:
     command:
        - yarn install
        - yarn run build
preMerge:
  env:
    USE_MONGODB: true
  pattern:
    - "./test/agenda.js"
postMerge:
  env:
    USE_MONGODB: true
  pattern:
    - "./test/agenda.js"
postRun:
     command:
        - yarn --version
version: 1.0
